// <auto-generated />
using System;
using ElohimShop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElohimShop.Infrastructure.Migrations
{
    [DbContext(typeof(ElohimShopDbContext))]
    partial class ElohimShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElohimShop.Domain.Entities.AdministradorPerfil", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId");

                    b.ToTable("AdministradorPerfil", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.ClientePerfil", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("UsuarioId");

                    b.ToTable("ClientePerfil", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Consulta", b =>
                {
                    b.Property<string>("IdConsulta")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_consulta");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_consulta");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_cliente");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Consulta", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.DetalleReservacion", b =>
                {
                    b.Property<string>("IdDetails")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_details");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("ProductoId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("producto_id");

                    b.Property<string>("ReservacionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reservacion_id");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal")
                        .HasComputedColumnSql("cantidad * precio_unitario", true);

                    b.HasKey("IdDetails");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("DetalleReservacion", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Marca", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nombre_marca");

                    b.HasKey("Id");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<string>("IdMetodoPago")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_metodo_pago");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nombre_metodo");

                    b.HasKey("IdMetodoPago");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Producto", b =>
                {
                    b.Property<string>("IdProducto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_producto");

                    b.Property<string>("CategoriaId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("IdMarca")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_marca");

                    b.Property<string>("ImagenPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("imagen_principal");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_producto");

                    b.Property<int>("Precio")
                        .HasColumnType("integer");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual");

                    b.HasKey("IdProducto");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.HasIndex("IdMarca");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Reservacion", b =>
                {
                    b.Property<string>("IdReservacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_reservacion");

                    b.Property<string>("ClienteId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoReservacion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_reservacion");

                    b.Property<string>("EstadoRenovacion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("estado_renovacion");

                    b.Property<DateTime>("FechaLimiteRetiro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite_retiro");

                    b.Property<DateTime>("FechaRenovacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_renovacion");

                    b.Property<string>("MetodoPagoId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("TotalRenovacion")
                        .HasColumnType("numeric")
                        .HasColumnName("total_renovacion");

                    b.HasKey("IdReservacion");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodigoReservacion")
                        .IsUnique();

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("Reservacion", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.TokenRevocado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokenRevocado", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Venta", b =>
                {
                    b.Property<string>("IdVenta")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_venta");

                    b.Property<string>("EstadoVenta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("estado_venta");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_venta");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total");

                    b.Property<string>("ReservacionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reservacion_id");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tipo_comprobante");

                    b.Property<string>("UsuarioCajeroId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_cajero_id");

                    b.HasKey("IdVenta");

                    b.HasIndex("ReservacionId")
                        .IsUnique();

                    b.HasIndex("UsuarioCajeroId");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.AdministradorPerfil", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Usuario")
                        .WithOne("AdministradorPerfil")
                        .HasForeignKey("ElohimShop.Domain.Entities.AdministradorPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.ClientePerfil", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Usuario")
                        .WithOne("ClientePerfil")
                        .HasForeignKey("ElohimShop.Domain.Entities.ClientePerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Cliente")
                        .WithMany("ConsultasCliente")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Administrador")
                        .WithMany("ConsultasAdministrador")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.DetalleReservacion", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesReservacion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElohimShop.Domain.Entities.Reservacion", "Reservacion")
                        .WithMany("Detalles")
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Producto");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Producto", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElohimShop.Domain.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Reservacion", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Cliente")
                        .WithMany("Reservaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElohimShop.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Reservaciones")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.TokenRevocado", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Venta", b =>
                {
                    b.HasOne("ElohimShop.Domain.Entities.Reservacion", "Reservacion")
                        .WithOne("Venta")
                        .HasForeignKey("ElohimShop.Domain.Entities.Venta", "ReservacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElohimShop.Domain.Entities.Usuario", "UsuarioCajero")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioCajeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Reservacion");

                    b.Navigation("UsuarioCajero");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Reservaciones");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesReservacion");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Reservacion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ElohimShop.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AdministradorPerfil");

                    b.Navigation("ClientePerfil");

                    b.Navigation("ConsultasAdministrador");

                    b.Navigation("ConsultasCliente");

                    b.Navigation("Reservaciones");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
